[package]
name = "svg_to_ahk"
version = "0.1.1"
edition = "2021"
authors = ["Perondas"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg2polylines = "0.6.0"
clap = "2.33.3"